-- When a batch was planned, which is not when its window closed.
--
-- The two coincide in steady state and diverge exactly when it matters: a
-- backfill anchors versions published days earlier, so measuring "how long has
-- this been waiting" against `window_end` would report every catch-up batch as
-- late from the moment it was created. The staleness alarm
-- (aptos-anchoring-proposal.md 4.8) needs the honest clock.
--
-- Nullable with a default: existing rows get the moment of the migration, which
-- is wrong by a day at most and cannot make anything look newer than it is.
ALTER TABLE "anchor_batch" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
