-- Anchoring loses its pause.
--
-- 0035 added a table so an operator could stop the workflow from the console.
-- It was one more thing anchoring owned, and anchoring is a side system that
-- has to come out cleanly (aptos-anchoring-proposal.md 4.1). Stopping it is
-- already possible without any of it: unset the APTOS_* entries and the
-- workflow finds itself unconfigured, which is the same switch every other
-- part of this feature answers to.
--
-- 0035 stays in the journal rather than being edited away. It ran; pretending
-- otherwise is how a migration history stops being usable.
DROP TABLE IF EXISTS "anchor_control";
